name: NuVote
version: ${project.version}
description: ${project.description}

author: Stephen McGregor
website: ${project.url}
main: nu.nerd.NuVote.NuVote
commands:
  vote:
    description: Vote for your opinion!
    permission: nuvote.vote
    default: true
    usage: |
           /vote <choice> [<choice>...] - Vote for an option
  vote-reload:
    description: Reload NuVote configuration
    permission: nuvote.admin
    default: op